include: package:flutter_lints/flutter.yaml

linter:
  rules:
    unawaited_futures: true
    discarded_futures: true
    prefer_single_quotes: true
    use_super_parameters: true
    non_constant_identifier_names: false
    use_build_context_synchronously: false

analyzer:
  exclude:
    - "**/*.g.dart"